pkgname=open-webui-lite-desktop
pkgver=0.1.0
pkgrel=1
pkgdesc="Open WebUI Lite Desktop Application"
arch=('x86_64' 'aarch64')
url="https://github.com/xxnuo/open-webui-lite"
license=('LICENSE')
depends=('cairo' 'desktop-file-utils' 'gdk-pixbuf2' 'glib2' 'gtk3' 'hicolor-icon-theme' 'libsoup' 'pango' 'webkit2gtk-4.1')
options=('!strip' '!emptydirs')
install=${pkgname}.install
source_x86_64=("${url}/releases/download/v${pkgver}/${pkgname}_${pkgver}_amd64.deb")
source_aarch64=("${url}/releases/download/v${pkgver}/${pkgname}_${pkgver}_arm64.deb")
